name: Website Builder
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'      
      - name: Build website
        run: |
          cd deepracer-on-the-spot/website
          npm ci
          npm install
          npm run build
          npm test
