name: Website Builder
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        run: |
          sudo apt install nodejs
      - name: Build website
        run: |
          pwd
          cd website
          npm ci
          npm install
          npm run build
          cd dist
          zip -r website.zip .
