name: Website Builder
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        run: |
          sudo apt install nodejs
      - name: Build website
        run: |
          pwd
          cd website
          npm ci
          npm install
          npm run build
          cd dist
          zip -r website.zip .
      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: website-zip
          path: website/dist/website.zip
      - name: Commit updated spot prices
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update website archive file" || echo "No changes to commit"
          git push